name: Rust

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run:
         sudo apt-get install gcc-mingw-w64-x86-64 -y
    - run:
        rustup target add x86_64-pc-windows-gnu
    - run:
        rustup target add x86_64-unknown-linux-gnu
    - name: Build windows
      run: cargo build --release --package MatiOsRunner --bin MatiOsRunner --target x86_64-pc-windows-gnu
    - run: mkdir result
    - run: mkdir result/windows_x64
    - name: Copy windows
      run: cp target/x86_64-pc-windows-gnu/release/MatiOsRunner.exe result/windows_x64/MatiOsRunner.exe
#    - name: Build linux
#      run: cargo build --release --package MatiOsRunner --bin MatiOsRunner --target x86_64-unknown-linux-gnu
#    - name: Copy linux
#      run: cp target/x86_64-unknown-linux-gnu/release/MatiOsRunner result/MatiOsRunner
    - name: Upload
      uses: actions/upload-artifact@v7
      with:
        name: matiosshell
        path: result
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: result/windows_x64/MatiOsRunner.exe
        asset_name: MatiOsRunner.exe
        tag: ${{ github.ref }}
        overwrite: true
